# Generated by Django 4.1.3 on 2022-11-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafrApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to=None)),
                ('date', models.DateField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
