# Generated by Django 4.1.3 on 2022-11-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safrecommerce', '0002_alter_safrapp_options_safrapp_price_safrapp_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safrapp',
            name='date',
        ),
        migrations.RemoveField(
            model_name='safrapp',
            name='done',
        ),
    ]
