# Generated by Django 4.1.3 on 2022-11-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safrecommerce', '0003_remove_safrapp_date_remove_safrapp_done'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SafrApp',
            new_name='SaffronProducts',
        ),
    ]
