# Generated by Django 4.1.3 on 2022-11-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safrecommerce', '0005_saffroonbginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saffroonbginfo',
            name='description',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
