# Generated by Django 4.1.3 on 2022-11-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safrecommerce', '0007_alter_saffroonbginfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saffronproducts',
            name='image',
            field=models.ImageField(upload_to='./SaffronECommerce/static/images/'),
        ),
    ]
