# Generated by Django 4.1.3 on 2022-11-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safrecommerce', '0008_alter_saffronproducts_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saffronproducts',
            options={'verbose_name': "Saffron's Product", 'verbose_name_plural': "Saffron's Products"},
        ),
    ]
