# Generated by Django 4.1.3 on 2022-11-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safrecommerce', '0009_alter_saffronproducts_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialOfferParameeters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='1st Commercial Offer', max_length=100)),
                ('minimalBulkWeight', models.DecimalField(decimal_places=2, default=100.0, max_digits=7)),
                ('wholesalePriceForGram', models.DecimalField(decimal_places=2, default=150.0, max_digits=7)),
                ('retailPriceForGram', models.DecimalField(decimal_places=2, default=150.0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Commercial offer parameters administration',
                'verbose_name_plural': 'Commercial offer parameters administration',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegramm', models.CharField(default='@EthanShagaei', max_length=50)),
            ],
            options={
                'verbose_name': "Saffron's History",
                'verbose_name_plural': "Saffrons's History",
            },
        ),
        migrations.CreateModel(
            name='CustomerOfferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('weight', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, default=4.0, max_digits=10)),
            ],
            options={
                'verbose_name': "Saffron's History",
                'verbose_name_plural': "Saffrons's History",
            },
        ),
    ]
