# Generated by Django 4.1.3 on 2022-11-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safrecommerce', '0011_contactinfo_phonenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerOfferModel',
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Contacts Data', 'verbose_name_plural': 'Contacts Data'},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(default='Ethan Shagaei', max_length=50),
        ),
    ]
