# Generated by Django 4.1.3 on 2022-11-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safrecommerce', '0012_delete_customeroffermodel_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saffronproducts',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='saffroonbginfo',
            options={'verbose_name': 'Information snippets', 'verbose_name_plural': 'Information snippet'},
        ),
    ]
