# Generated by Django 4.1.3 on 2022-11-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safrecommerce', '0013_alter_saffronproducts_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialofferparameeters',
            options={'verbose_name': 'Commercial offer', 'verbose_name_plural': 'Commercial offers'},
        ),
        migrations.AlterModelOptions(
            name='saffroonbginfo',
            options={'verbose_name': 'Block with information', 'verbose_name_plural': 'Blocks with information'},
        ),
        migrations.AlterField(
            model_name='commercialofferparameeters',
            name='retailPriceForGram',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=7),
        ),
    ]
