# Generated by Django 4.1.3 on 2022-11-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safrecommerce', '0014_alter_commercialofferparameeters_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saffronproducts',
            name='image',
            field=models.ImageField(upload_to='./static/images/'),
        ),
        migrations.AlterField(
            model_name='saffroonbginfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='./static/images/'),
        ),
    ]
