# Generated by Django 4.1.3 on 2022-11-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safrecommerce', '0015_alter_saffronproducts_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialofferparameeters',
            name='minimalBulkWeight',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commercialofferparameeters',
            name='retailPriceForGram',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commercialofferparameeters',
            name='wholesalePriceForGram',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saffronproducts',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='saffronproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='saffroonbginfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
    ]
