# Generated by Django 4.1.3 on 2022-11-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safrecommerce', '0016_alter_commercialofferparameeters_minimalbulkweight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saffronproducts',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='saffronproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saffronproducts',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saffroonbginfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='./static/images/'),
        ),
    ]
