# Generated by Django 4.1.3 on 2022-11-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safrecommerce', '0019_alter_saffronproducts_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saffronproducts',
            old_name='weight',
            new_name='weightInGr',
        ),
        migrations.AddField(
            model_name='saffronproducts',
            name='weightInSot',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saffroonbginfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
