# Generated by Django 4.1.3 on 2022-12-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safrecommerce', '0023_alter_customeroffermodel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeroffermodel',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
    ]
