# Generated by Django 4.1.3 on 2022-12-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safrecommerce', '0026_customeroffermodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeroffermodel',
            name='totalPrice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
